var testQuestions = [
    // のときあひりくむゆたろもはへてふぬ
    {
        id: "0",
        name: "q0",
        symbol: "ぬ",
        answers: ["fu", "no", "nu"],
        correctAnswer: "nu",
    },
    {
        id: "1",
        name: "q1",
        symbol: "き",
        answers: ["ki", "go", "me"],
        correctAnswer: "ki",
    },
    {
        id: "2",
        name: "q2",
        symbol: "の",
        answers: ["sa", "no", "he"],
        correctAnswer: "no",
    },
    {
        id: "3",
        name: "q3",
        symbol: "と",
        answers: ["yo", "to", "ge"],
        correctAnswer: "to",
    },
    {
        id: "4",
        name: "q4",
        symbol: "あ",
        answers: ["a", "mo", "yu"],
        correctAnswer: "a",
    },
    {
        id: "5",
        name: "q5",
        symbol: "ひ",
        answers: ["mu", "ta", "hi"],
        correctAnswer: "hi",
    },
    {
        id: "6",
        name: "q6",
        symbol: "ふ",
        answers: ["fu", "wa", "ku"],
        correctAnswer: "fu",
    },
    {
        id: "7",
        name: "q7",
        symbol: "く",
        answers: ["a", "ku", "to"],
        correctAnswer: "ku",
    },
    {
        id: "8",
        name: "q8",
        symbol: "む",
        answers: ["su", "no", "mu"],
        correctAnswer: "mu",
    },
    {
        id: "9",
        name: "q9",
        symbol: "ゆ",
        answers: ["me", "a", "yu"],
        correctAnswer: "yu",
    },
    {
        id: "10",
        name: "q10",
        symbol: "た",
        answers: ["ta", "ke", "hi"],
        correctAnswer: "ta",
    },
    {
        id: "11",
        name: "q11",
        symbol: "ろ",
        answers: ["sa", "ro", "na"],
        correctAnswer: "ro",
    },
    {
        id: "12",
        name: "q12",
        symbol: "も",
        answers: ["ya", "mo", "re"],
        correctAnswer: "mo",
    },
    {
        id: "13",
        name: "q13",
        symbol: "は",
        answers: ["ke", "no", "ha"],
        correctAnswer: "ha",
    },
    {
        id: "14",
        name: "q14",
        symbol: "へ",
        answers: ["ku", "ni", "he"],
        correctAnswer: "he",
    },
    {
        id: "15",
        name: "q15",
        symbol: "て",
        answers: ["i", "ke", "te"],
        correctAnswer: "te",
    },
    /*{
        id: "6",
        name: "q6",
        symbol: "り",
        answers: ["ri", "no", "he"],
        correctAnswer: "ri",
    }*/
]

export default testQuestions;