# Generated by Django 2.2 on 2019-05-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='practice',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='test',
            field=models.IntegerField(),
        ),
    ]
