# Generated by Django 2.2 on 2019-05-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20190523_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='practice',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='test',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
