# Generated by Django 2.2 on 2019-05-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20190523_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='users_answer',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
