# Generated by Django 2.2 on 2019-06-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20190620_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
